version: '3'
services:
  victim:
    build: .
    networks:
      internal_net:
    ports:
      - "8080:80"

  backup:
    build:
      context: ./backup
    networks:
      internal_net:
    ports:
      - "2222:22"
    depends_on:
      - victim

networks:
  internal_net:
    driver: bridge
